### ISSUE TITLE
Do not log redshift credentials to stdout

### ISSUE THREAD

**Issue by Limess** [transferwise/pipelinewise-target-redshift#9]
## Issue 

Currently credentials are logged to stdout:

```
COPY public.my_table ("_SDC_BATCHED_AT", "_SDC_DELETED_AT", "_SDC_EXTRACTED_AT", "SOME_COLUMN", "PK", "UPDATED_AT") FROM 's3://my_s3_bucket/__tmp/pipelinewise_public-my_table_20190918-105311-945010.csv'
ACCESS_KEY_ID '*********************'
SECRET_ACCESS_KEY '****************************************'
DELIMITER ',' REMOVEQUOTES ESCAPE
BLANKSASNULL TIMEFORMAT 'auto'
COMPUPDATE OFF STATUPDATE OFF
```

Where the `*` characters are actual credentials.
This is undesirable as it means the keys are propagated to other logging systems, e.g airflow in our case.

## Expected

Credentials are redacted, likely as `*` characters.

**Comment by koszti** [comment]
Fixed by https://github.com/transferwise/pipelinewise-target-redshift/commit/01e9ea146b6885c31e67c6f144b38e30e5e43ed7

Generated SQLs are only visible in debug mode and not in the default info level.

**If you use target-redshift alone**: You'll not see credentials in the log
**If you use target-redshift with [PipelineWise](https://transferwise.github.io/pipelinewise)**: You'll see redshift credentials in the log when [FastSync](https://transferwise.github.io/pipelinewise/concept/fastsync.html) to Redshift is triggered. Enhancing logging is currently in progress and keep this issue open until it's not fixed everywhere in PipelineWise.
